apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ai-agents
  labels:
    app: api-gateway
    component: ai-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: ai-gateway
    spec:
      containers:
      - name: api-gateway
        image: gcr.io/hackgkfinalv1/api-gateway:minimal
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: FRONTEND_URL
          value: "http://frontend.default.svc.cluster.local"
        - name: MCP_URL
          value: "http://mcp-server.ai-agents.svc.cluster.local:8080"
        - name: A2A_URL
          value: "http://a2a-orchestrator.ai-agents.svc.cluster.local:8081"
        - name: PORT
          value: "8090"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: ai-agents
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8090
    name: http