apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-mcp
  labels:
    app: product-catalog-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-mcp
  template:
    metadata:
      labels:
        app: product-catalog-mcp
    spec:
      containers:
      - name: product-catalog-mcp
        image: us-central1-docker.pkg.dev/gke10-final/boutique-ai-repo/product-catalog-mcp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-mcp
  labels:
    app: product-catalog-mcp
spec:
  selector:
    app: product-catalog-mcp
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
